#!/usr/bin/env php

<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
  require __DIR__.'/../../autoload.php';
} else {
  require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('ib3 Drupal Installer', '1.0.1');
$app->add(new ib3\Installer\Console\NewCommand);
$app->run();
